name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submitting your first issue! Be sure that you have properly filled out the template so that the issue can be resolved as quickly as possible."
        pr-message: "Thanky ou for submitting you rfirst pull request! Your contribution is highly appreciated and will be reveiwed as soon as possible. Please ensure that your request meets the guidelines set in CONTRIBUTING.md"
